### ISSUE TITLE
Invalid JSON

### ISSUE THREAD

**Issue by emadd** [blitline-dev/simple_blitline_node#10]
Not sure if this is a problem in this module or the service itself:

```
undefined:1
tp://s3.amazonaws.com/mybucket/user/1234/7a7DrON-sm.jpg"}],"job_id":,"3kgnMhrT
                                                                    ^
SyntaxError: Unexpected token ,
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/Users/erikmadsen/Documents/Projects/Server/node_modules/simple_blitline_node/lib/blitline.js:43:32)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)
```

**Comment by emadd** [comment]
Still having issues with this.  Starting to consider another service.

```
,"s3_url":"http://s3.amazonaws.com/quiverus/user/1/5EkPdNX-sm.jpg"},],"job_id"
                                                                    ^
SyntaxError: Unexpected token ]
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/Users/erikmadsen/Documents/Projects/Quiver2-Server/node_modules/simple_blitline_node/lib/blitline.js:43:32)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)
```

**Comment by blitline-dev** [comment]
Apologies. We have failed to push the latest updates here to npm. We have just done so. If possible, please try updating your simple_blitline_node version. We will set up some integration testing to make sure we aren't seeing this issue with JSON results in other categories.

**Comment by emadd** [comment]
I'm not having any luck posting jobs with either 2.3.1 or 2.3.2.  The result callback is never called.  Running Node 4.4.5

**Comment by emadd** [comment]
Never mind.  You guys switched to promises but haven't updated your docs.
